name: Upload documentation

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build HTML
        run: bin/gradle dokkaHtmlMultiModule --no-daemon --stacktrace

      - name: List dokka HTML output
        run: ls -lR build/dokka/html

      - name: Check Dokka output exists
        run: test -d build/dokka/html || (echo "Dokka output not found!" && exit 1)

      - name: Upload HTML
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/dokka/html
          name: 'github-pages'

      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v3
        with:
          artifact_name: github-pages
