name: Test

on:
  pull_request:
  push:
    branches:
      - main

env:
  ENVIRONMENT: TESTING
  TERM: dumb

jobs:
  jvm:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        cmd:
          - bin/gradle clean build -i --scan --no-daemon

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: ${{ matrix.cmd }}

      - name: Publish Test Report
        if: ${{ always() }}
        uses: mikepenz/action-junit-report@a83fd2b5d58d4fc702e690c1ea688d702d28d281
        with:
          check_name: Test Report - ${{ matrix.cmd }}
          report_paths: '**/build/test-results/test/TEST-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
